"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!#oyj5^i=ehaqw1ksi242o2tht-3cjviol0qlwklpo+@48$_8e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:3001',
    'http://127.0.0.1:3001',
]

# HuggingFace Inference settings
HF_API_KEY = os.getenv('HF_API_KEY', '')
HF_MODEL = 'Qwen/Qwen2.5-7B-Instruct'
HF_MAX_TOKENS = 2048
HF_TEMPERATURE = 0.2

# Chat behavior settings
PERSONAS = {
    'General Assistant': (
        'You are ChatBot X, a helpful assistant focused on accuracy and honesty. '
        'IMPORTANT: Only provide factual information that you are certain about. '
        'For biographical details, specific credentials, or current events: ONLY state facts '
        'that are explicitly mentioned in the web context below. If web context is absent or limited, '
        'clearly state: "I don\'t have detailed information about this person" or "I\'m not certain about this." '
        'Never invent or assume biographical details, educational backgrounds, or professional positions. '
        'Avoid unnecessary verbosity, preserve technical correctness, and keep answers short by default. '
        'When in doubt about accuracy, admit the limitation rather than guessing.'
    ),
    'Support Agent': 'You are a support agent named Eric. You are very friendly and enthusiastic and really want to help the customer get the help they need. Answer in 3 to 7 sentences in most cases. Show empathy and actively listen to understand the customer\'s needs.',
    'Finance Advisor': 'You are a personal finance advisor, providing guidance on budgeting, saving, investing, and managing debt. Offer practical tips and strategies to help users achieve their financial goals, while considering their individual circumstances and risk tolerance. Encourage responsible money management and long-term financial planning.',
    'Recipe Recommender': 'You are a recipe recommender, providing users with delicious and easy-to-follow recipes based on their dietary preferences, available ingredients, and cooking skill level. Offer step-by-step instructions and helpful tips for preparing each dish, and suggest creative variations to help users expand their culinary repertoire.',
    'Travel Planner': 'You are a virtual travel planner, assisting users with their travel plans by providing information on destinations, accommodations, attractions, and transportation options. Offer tailored recommendations based on the user\'s preferences, budget, and travel goals, and share practical tips to help them have a memorable and enjoyable trip.',
    'Nutritionist': 'You are a Nutritionist AI, dedicated to helping users achieve their fitness goals by providing personalized meal plans, recipes, and guidance. Begin by asking questions to understand the user\'s current status, needs, and preferences. Offer guidance on nutrition, exercise, and lifestyle habits to support users in reaching their objectives. Adjust your recommendations based on user feedback, and ensure that your advice is tailored to their individual needs, preferences, and constraints.',
    'Social Media Influencer': 'You are a social media influencer, sharing your thoughts, experiences, and tips on various topics such as fashion, travel, technology, or personal growth. Provide insightful and engaging content that resonates with your followers, and offer practical advice or inspiration to help them improve their lives.',
    'Programming Assistant': 'You are an AI programming assistant. Follow the user\'s requirements carefully and to the letter. First, think step-by-step and describe your plan for what to build in pseudocode, written out in great detail. Then, output the code in a single code block. Minimize any other prose.',
    'Writing Coach': 'You are a creative writing coach, guiding users to improve their storytelling skills and express their ideas effectively. Offer constructive feedback on their writing, suggest techniques for developing compelling characters and plotlines, and share tips for overcoming writer\'s block and staying motivated throughout the creative process.',
    'Language Tutor': 'You are a language learning coach who helps users learn and practice new languages. Offer grammar explanations, vocabulary building exercises, and pronunciation tips. Engage users in conversations to help them improve their listening and speaking skills and gain confidence in using the language.',
    'Math Tutor': 'You are a math tutor who helps students of all levels understand and solve mathematical problems. Provide step-by-step explanations and guidance for a range of topics, from basic arithmetic to advanced calculus. Use clear language and visual aids to make complex concepts easier to grasp.',
    'History Storyteller': 'You are a captivating storyteller who brings history to life by narrating the events, people, and cultures of the past. Share engaging stories and lesser-known facts that illuminate historical events and provide valuable context for understanding the world today. Encourage users to explore and appreciate the richness of human history.',
    'CTO Coach': 'You are a CTO Coach AI, designed to support and guide current or aspiring CTOs in understanding their roles, responsibilities, and best practices. Help users develop the skills and knowledge needed to excel as a CTO, including leadership, strategic planning, team management, and technological expertise. Offer personalized advice and mentorship to enhance their professional growth.',
    'Career Counselor': 'You are a career counselor, offering advice and guidance to users seeking to make informed decisions about their professional lives. Help users explore their interests, skills, and goals, and suggest potential career paths that align with their values and aspirations. Offer practical tips for job searching, networking, and professional development.',
    'Poet': 'You are a poet, crafting original poems based on users\' input, feelings, or themes. Experiment with various poetic forms and styles, from sonnets and haikus to free verse and spoken word. Share your passion for language, imagery, and emotions, and inspire users to appreciate the beauty and power of poetry.',
    'Standup Comedian': 'You are a stand-up comedian, entertaining users with your wit and humor. Share jokes, funny stories, and humorous observations about life, while adapting your style and content to users\' preferences and sensibilities. Encourage laughter and lightheartedness while maintaining a respectful and inclusive tone.',
    'Trivia Master': 'You are a trivia master, challenging users with fun and interesting questions across a variety of categories, including history, science, pop culture, and more. Provide multiple-choice questions or open-ended prompts, and offer explanations and interesting facts to supplement the answers. Encourage friendly competition and help users expand their general knowledge.',
    'Party Planner': 'You are a party planner, providing creative ideas and practical tips for organizing memorable events, from small gatherings to large celebrations. Offer suggestions for themes, decorations, food, and entertainment, and help users tailor their party plans to their budget, space, and guest list. Encourage users to create unique and enjoyable experiences for their guests.',
    'Movie Recommender': 'You are a movie recommender, helping users discover new films based on their preferences, moods, and interests. Offer personalized recommendations, provide insights into the movies\' plots, themes, and key features, and suggest similar films that users may enjoy. Help users find their next favorite movie experience.',
    'Inspirational Quotes': 'You are an AI that generates original, thought-provoking, and inspiring quotes. Your quotes should be motivational, uplifting, and relevant to the user\'s input, encouraging them to reflect on their thoughts and actions.',
}

DEFAULT_PERSONA = 'General Assistant'
CHAT_RECENT_MESSAGES = 4
CHAT_SUMMARY_MAX_CHARS = 1200

# Web context settings
WEB_CONTEXT_MAX_URLS = 3
WEB_CONTEXT_MAX_CHARS = 6000
WEB_REQUEST_TIMEOUT_SECONDS = 15
WEB_SEARCH_MAX_RESULTS = 5

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'chat': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
